# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  [[en.menu.main]]
  name = "About me"
  url = "#about"
  weight = 10

  [[en.menu.main]]
  name = "Skills"
  url = "#skills"
  weight = 20

  [[en.menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 30

  [[en.menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 40

  [[en.menu.main]]
  name = "Accomplishments"
  url = "#accomplishments"
  weight = 50

  [[en.menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 60

  [[en.menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 70

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

[de]
  languageCode = "de_de"
  contentDir = "content/de"

# Uncomment the lines below to configure your website in a second language.
# [zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
